cars/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('cars/', views.cars_list, name='cars_list'),
    path('car/<int:id>/', views.car_detail, name='car_detail'),
    path('car/reserve/<int:id>/', views.car_reserve, name='car_reserve'),
    path('profile/', views.user_profile, name='profile'),
    path('search/', views.search, name='search_cars'),
    path('payment/', views.payment, name='payment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cars.urls')),
    path('', include('pages.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/models.py
from django.db import models
from django.conf import settings
from django_jalali.db import models as jmodels
from datetime import timedelta, datetime


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی'

    def __str__(self):
        return f'{self.name}'


class Car(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=255)
    model = models.CharField(max_length=500)
    number_plate = models.CharField(max_length=255)
    color = models.CharField(max_length=255)
    car_image = models.ImageField(upload_to='cars/cars_image/', default='cars/cars_image/default.png')
    price = models.PositiveIntegerField()

    class Meta:
        verbose_name = 'ماشین'
        verbose_name_plural = 'ماشین'
        ordering = ['id']

    def __str__(self):
        return f'{self.name}'


class Reservation(models.Model):
    PAID = 'p'
    UNPAID = 'up'
    PAYMENT_STATUS = [
        (PAID, 'پرداخت شده'),
        (UNPAID, 'پرداخت نشده')
    ]

    WITH_DRIVER = 'wd'
    WITHOUT_DRIVER = 'wod'

    DRIVER_STATUS = [
        (WITH_DRIVER, 'با راننده'),
        (WITHOUT_DRIVER, 'بدون راننده'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    car = models.ForeignKey(Car, on_delete=models.PROTECT)
    driver = models.CharField(verbose_name='راننده', max_length=3, choices=DRIVER_STATUS, default=WITH_DRIVER)
    start_date = jmodels.jDateField(verbose_name='تاریخ شروع', default=datetime.today())
    end_date = jmodels.jDateField(verbose_name='تاریخ پایان', default=datetime.today() + timedelta(days=2))
    delivery_address = models.CharField(verbose_name='آدرس محل تحویل', max_length=500)
    is_paid = models.CharField(max_length=6, choices=PAYMENT_STATUS, default=UNPAID)

    class Meta:
        verbose_name = 'رزرو'
        verbose_name_plural = 'رزرو'

    def __str__(self):
        return f'{self.user} : {self.car}'

templates/banner.html
{% load static %}

<div id="banner-header" class="mb-4">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-12 div-img">
                <img class="mt-md-5 mt-lg-6 mt-5" src="{% static 'img/car-rent-befarman.png' %}" alt="">
            </div>
            <div class="mt-lg-6 col-md-6 mt-md-5 mt-sm-0 col-sm-12 ">
                <h1>بفرمان<br>
                    اپلیکیشن تخصصی اجاره خودرو
                    مردم به مردم
                </h1>
                <p>سامانه اجاره خودروی بفرمان با شعار ” هر محله یک ایستگاه“، امکان اجاره دادن خودرو توسط مالک و
                    اجاره کردن آن توسط سایر
                    مردم را فراهم کرده است. با استفاده از این اپلیکیشن، هر مکانی که هستید می توانید خودروی خود را
                    اجاره بدهید و همین طور می‌
                    توانید خودرو دلخواه خود را اجاره کنید.</p>
            </div>
        </div>
    </div>
</div>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />

  <title>{% block title %}{% endblock title %}</title>


  <link rel="stylesheet" href="{% static 'style/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'style/bootstrap-icons.min.css' %}">
  <link rel="stylesheet" href="{% static 'style/main-style.css' %}">


</head>

<body>

  {% block block_header %}
  {% include 'navbar.html' %}

  {% if banner != False %}
  {% include 'banner.html' %}

  {% endif %}
  {% endblock %}


  {% block body %}
  {% endblock body %}



  {% include 'footer.html' %}


  <script src="{% static 'script/jquery-3.5.1.js' %}"></script>
  <script src="{% static 'script/bootstrap.js' %}"></script>
  <script src="{% static 'script/main-script.js' %}"></script>

  {% block script %}

  {% endblock %}
</body>

</html>

templates/footer.html
{% load static %}

<div id="footer" class="">
    <div class="container">
        <div class="row">
            <div class="col-12 d-flex flex-wrap justify-content-center align-self-center">
                <div class="d-inline-flex mx-3">
                    <img src="{% static 'img/enamad.png' %}" alt="enamad" width="125">
                </div>
                <div class="d-inline-flex mx-3">
                    <img src="{% static 'img/samandehi.png' %}" alt="samandehi" width="125">
                </div>
                <div class="d-inline-flex mx-3">
                    <img src="{% static 'img/enamad.png' %}" alt="" width="125">
                </div>
            </div>
            <p class="text-center col-12">© کلیه حقوق مادی و معنوی این سایت متعلق به ما می باشد</p>
        </div>
    </div>
</div>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Logo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
            aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav ms-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">خانه</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cars_list' %}">رزرو ماشین</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'search_cars' %}">دسته بندی</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'page' 'aboutus' %}">درباره ما</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'page' 'contactus' %}">ارتباط با ما</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'questions_list'%}">سوالات متداول</a>
                </li>

                {% if not request.user.is_authenticated %}
                <li class="nav-item {% if request.resolver_match.view_name == 'login' %}active{%endif%}">
                    <a href="{% url 'login' %}" class="nav-link">ورود</a>
                </li>
                <li class="nav-item {% if request.resolver_match.view_name == 'signup' %}active{%endif%}">
                    <a href="{% url 'signup' %}" class="nav-link">ثبت نام</a>
                </li>
                {% else %}

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdownUser" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        کاربری
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarScrollingDropdownUser">

                        <li class=" {% if request.resolver_match.view_name == 'profile' %}active{%endif%}">
                            <a href="{% url 'profile' %}" class="dropdown-item">پروفایل</a>
                        </li>
                        <li class="">
                            <a href="{% url 'password_change' %}" class="dropdown-item">تغییر رمز عبور</a>
                        </li>
                        <li class="">
                            <a href="{% url 'password_reset' %}" class="dropdown-item">فراموشی رمز عبور</a>
                        </li>
                        <li class=" {% if request.resolver_match.view_name == 'logout' %}active{%endif%}">
                            <form method="post" action="{% url 'logout' %}" style="">
                                {% csrf_token %}
                                <input style="background: #00000000;border: none;" type="submit" class="dropdown-item"
                                    value="خروج">
                            </form>
                        </li>
                    </ul>
                </li>
                {% endif %}
            </ul>
            <form class="d-flex" action="{% url 'search_cars' %}">
                <input class="form-control ms-2" name="q" type="search" placeholder="جستجو" aria-label="جستجو"
                    value="{% if query %}{{ query }}{% endif %}">
                <button class="btn btn-primary text-nowrap" type="submit">پیدا کن</button>
            </form>
        </div>
    </div>
</nav>

templates/pagination.html
{% load pagination_tags %}

<nav aria-label="Page navigation">
  <ul class="pagination">
    {% if page.number != 1 %}
    <li class="page-item">
      <a class="page-link" href="?{% url_replace page=1 %}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}
    {% for page_number in pagens %}
    {% if page_number in page.paginator.page_range %}
    <li class="page-item {% if page_number == page.number %}active{% endif %}">
      <a class="page-link" href="?{% url_replace page=page_number %}">
        {{page_number}}
      </a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.number != last_page %}
    <li class="page-item">
      <a class="page-link" href="?{% url_replace page=last_page %}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>

templates/profile.html
{% extends "base.html" %}

{% block title %}Profile{% endblock title %}


{% block body %}
<div class="div-mid">
    <div class="container my-5">
        <div class="row">
            <div class="col-10 row mx-auto">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">نام ماشین</th>
                            <th scope="col">تاریخ رزرو</th>
                            <th scope="col">تاریخ پایان</th>
                            <th scope="col">ادرس محل تحویل</th>
                            <th scope="col">راننده</th>
                            <th scope="col">پرداخت شده</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for car_reserve in cars_reserve %}
                        <tr>
                            <th scope="row">1</th>
                            <td>{{ car_reserve.car.name }}</td>
                            <td>{{ car_reserve.start_date }}</td>
                            <td>{{ car_reserve.end_date }}</td>
                            <td>{{ car_reserve.delivery_address }}</td>
                            <td>
                                {{ car_reserve.get_driver_display }}

                            </td>
                            <td>{{ car_reserve.get_is_paid_display }}</td>
                        </tr>
                        
                        
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="div-mid">
    <div class="container my-5">
        <div class="row big-card">
            <div class="col-6 row mx-auto">
                <div class="col-3 big-card-right"></div>
                <div class="col-9 big-card-left">
                    <h4 class="mb-3">اطلاعات کاربری</h4>
                    <ul class="list-group list-group-flush mb-3">
                        <li class="list-group-item">نام کاربری: <span>{{ user.username }}</span></li>
                        <li class="list-group-item">اسم کوچک: <span>{{ user.first_name }}</span></li>
                        <li class="list-group-item">نام خانوادگی: <span>{{ user.last_name }}</span></li>
                        <li class="list-group-item">سن: <span>{{ user.age }}</span></li>
                    </ul>
                    <a class="btn btn-primary" href="{% url 'password_change' %}">تغییر پسورد</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}